# --- Build stage ---
FROM node:18-alpine AS build
WORKDIR /app
COPY package.json ./
RUN npm install --production
COPY src ./src

# --- Runtime stage ---
FROM node:18-alpine
WORKDIR /app
COPY --from=build /app /app
ENV PORT=4001
EXPOSE 4001
CMD ["node", "src/index.js"]
